### PR TITLE
Add integration tests for EEG BIDS import

### PR DESCRIPTION
**Pull request by MaximeBICMTL**
Extracted from #1325

## Description

Add integration tests for EEG BIDS import.

For the tests to pass, this PR requires to add the `Face13` BIDS dataset to the test S3 bucket as `incoming/Face13`. Only the `sub-OTT166` subject is required, the `participants.tsv` file should contain this:

```tsv
participant_id	cohort	site	project
sub-OTT166	Fresh	OTT	PUMP
```

This PR also adds the ability to use project aliases when using `--createsession` in the current BIDS importer to be consistent with the new BIDS importer.

## Description 2

Since the tests did not work at first, I also added a bugfix in this PR to make the code work with the most recent `mne` version (1.11.0). Note that the code no longer works with the previous version (1.10.x or less).

### CODE REVIEW

**Review by jeffersoncasimir — CHANGES_REQUESTED** [review]
I am getting this error:

```
Traceback (most recent call last):
  File "/opt/Loris-MRI/bin/mri/python/loris_eeg_chunker/edf_to_chunks.py", line 43, in <module>
    file_type=mne_edf.FileType.EDF,
              ^^^^^^^^^^^^^^^^
AttributeError: module 'mne.io.edf.edf' has no attribute 'FileType'
```

`mne==1.10.2`

Works with latest version (1.11.0). Changed to approved
